mode: SHADOW
logging:
  level: info
  json: true
services:
  agentCore:
    port: 4010
  executor:
    port: 4011
  uiGateway:
    port: 3000
  socialIngestor:
    port: 4012
  onchainDiscovery:
    port: 4013
  safetyEngine:
    port: 4014
  policyEngine:
    port: 4015
  alphaRanker:
    port: 4021
  positionManager:
    port: 4016
  narrativeMiner:
    port: 4017
  migrationWatcher:
    port: 4018
  leaderWallets:
    port: 4019
    metricsPort: 8110
  featuresJob:
    port: 4020
  priceUpdater:
    port: 4022
  rpcMonitor:
    port: 4023
  metrics:
    port: 8090
endpoints:
  agentCore:
    baseUrl: http://127.0.0.1:4010
  executor:
    baseUrl: http://127.0.0.1:4011
  socialIngestor:
    baseUrl: http://127.0.0.1:4012
  policyEngine:
    baseUrl: http://127.0.0.1:4015
  safetyEngine:
    baseUrl: http://127.0.0.1:4014
  onchainDiscovery:
    baseUrl: http://127.0.0.1:4013
  alphaRanker:
    baseUrl: http://127.0.0.1:4021
  positionManager:
    baseUrl: http://127.0.0.1:4016
  narrativeMiner:
    baseUrl: http://127.0.0.1:4017
  migrationWatcher:
    baseUrl: http://127.0.0.1:4018
  leaderWallets:
    baseUrl: http://127.0.0.1:4019
  featuresJob:
    baseUrl: http://127.0.0.1:4020
  priceUpdater:
    baseUrl: http://127.0.0.1:4022
  rpcMonitor:
    baseUrl: http://127.0.0.1:4023
  metrics:
    baseUrl: http://127.0.0.1:8090
gating:
  lpMinSol: 18                   # Require deeper pools before safety (retrained rugguard guidance)
  buysSellRatioMin: 1.7          # Stricter flow balance to cut wash-trading entries
  uniquesMin: 12                 # Restore higher trader diversity minimum
  minPoolAgeSec: 20              # Small bump to let authority changes propagate
  maxSpreadBps: 220              # Tighter spread gate based on updated slip calibration
watchWindows:
  durationSec: 1200
  refreshIntervalSec: 5
  decayHalfLifeSec: 120
topics:
  cluster:
    lshBands: 12
    lshRows: 6
    minCosine: 0.82
    mergeMinObservations: 3
  scoring:
    openThreshold: 0.6
    sustainThreshold: 0.45
    recencyHalfLifeSec: 120
    noveltyEpsilon: 0.000001
  phrase:
    minLength: 3
    maxLength: 48
    stopwords:
      - the
      - and
      - for
      - with
      - that
      - this
      - have
      - from
      - your
      - about
      - into
      - just
      - over
      - they
      - what
      - when
      - where
      - will
      - make
      - going
      - been
      - take
      - like
      - want
  matching:
    minTrieScore: 0.5
    minCosine: 0.75
    boostSymbolMatch: 0.15
    coolDownSec: 60
  baseline:
    halfLifeSec: 604800
    flushIntervalSec: 300
  test:
    enabled: false
ladders:
  takeProfits: [0.25, 0.3, 0.25, 0.2]       # Balanced scalp: 25%, 30%, 25%, 20% exits
  multiplierPercents: [40, 80, 150, 400]    # Profitable at 40%, great at 80%, moonshots at 400%
  trailActivatePct: 80                       # Activate trailing at 80% gain  
  trailPct: 30                               # 30% trailing stop (balanced)
  hardStopLossPct: 25                        # 25% hard stop loss
bandit:
  rewardHorizonMinutes: 30
  updateIntervalSec: 20
  epsilonFloor: 0.02
  bundles:
    - id: moonshot-hunter
      label: Moonshot Hunter
      gate: loose
      slippageBps: 500
      tipPercentile: p75
      sizeMultiplier: 1.5
    - id: vampire-attack
      label: Vampire Attack
      gate: loose
      slippageBps: 800
      tipPercentile: p90
      sizeMultiplier: 2.0
    - id: fast-entry
      label: Fast Entry
      gate: normal
      slippageBps: 300
      tipPercentile: p50
      sizeMultiplier: 1.0
    - id: alpha-chase
      label: Alpha Chase
      gate: loose
      slippageBps: 1000
      tipPercentile: p90
      sizeMultiplier: 1.2
wallet:
  reservesSol: 0.1                   # Keep 0.1 SOL reserve for fees/gas
  dailySpendCapPct: 0.8              # Use up to 80% of account per day
  autoSkimProfitSol: 0.5
  perNameCapFraction: 0.2            # Max 20% of account per token (safer)
  perNameCapMaxSol: null             # No hard cap - let percentage govern
  lpImpactCapFraction: 0.03          # 3% of LP pool max impact
  flowCapFraction: 0.6               # 60% of flow capacity
  flowTradesPer5m: 60                # Reference trade count (5m window) for full flow allowance
  flowCapMinSol: 0.0                 # Minimum SOL capacity used if flow-based estimate is zero
  # Percentage-based position sizing (% of total account equity)
  equityTiers:
    - minEquity: 0
      maxEquity: 5
      riskFraction: 0.15             # 15% of account per position (small accounts)
    - minEquity: 5  
      maxEquity: 20
      riskFraction: 0.12             # 12% of account per position (medium accounts)
    - minEquity: 20
      maxEquity: 100
      riskFraction: 0.10             # 10% of account per position (large accounts)
    - minEquity: 100
      maxEquity: null
      riskFraction: 0.08             # 8% of account per position (whale accounts)
  concurrencyCap: 4                  # Baseline: tighten to 4 concurrent positions while hardening
  concurrencyScaler:
    base: 1
    max: 1.4
    recoveryMinutes: 60
rpc:
  primaryUrl: http://127.0.0.1:8899
  secondaryUrl: ''
  wsUrl: ''
  jitoHttpUrl: ''
  jitoGrpcUrl: ''
  jitoTipAccount: ''
  jupiterBaseUrl: https://quote-api.jup.ag/v6
  httpHeaders: {}
execution:
  tipStrategy: auto
  computeUnitPriceMode: auto_oracle
  migrationPreset:
    enabled: true
    durationMs: 60000
    cuPriceBump: 3000
    minSlippageBps: 100
    decayMs: 30000
  routeQuarantine:
    windowMinutes: 1440
    minAttempts: 8
    failRateThreshold: 0.25
    slipExcessWeight: 0.5
    failRateWeight: 100
dataProviders:
  neynarBaseUrl: https://api.neynar.com
  dexscreenerBaseUrl: https://api.dexscreener.com
  birdeyeBaseUrl: https://public-api.birdeye.so
  blueskyJetstreamUrl: wss://jetstream2.us-east.host.bsky.network
  gdeltPulseUrl: https://api.gdeltproject.org/api/v2/summary/summary
safety:
  lpBurnThreshold: 0.7             # Keep: Reasonable for memecoins (was 0.9)
  holderTopCap: 0.25               # Balanced: Less whale risk (was 0.35, originally 0.2)
  lockerPrograms:
    - 6z7H14RTa7tD1ynjUTduV1JN9WewtGku5Kz4DKftd84f
    - Lock111111111111111111111111111111111111111
    - 87AxbZcq7aj3HyCuXapnwXCfJLLq5yRvCNr4ieVsg7fR
  ignoreAccounts:
    - 1nc1nerator11111111111111111111111111111111
  candidateFeedUrl: null
  # Fast-entry safety minimums - never skip these even for trending tokens
  fastEntry:
    sssThreshold: 6.0              # Raised from 5.0 - higher bar for fast-entry
    velocityThreshold: 2.5         # Raised from 2.0 - require stronger momentum  
    minimumChecks:
      lpMinSol: 14                 # Fast mode still enforces deeper pools post-rugguard retrain
      uniquesMin: 10               # Keep diversity floor close to mainline gate
      lpBurnThreshold: 0.6         # Always require 60%+ LP burn even in fast mode
      maxRugProb: 0.85             # Reject fast entries with high rug likelihood
      holderTopCap: 0.35           # Slightly lower whale concentration allowance

policy:
  safeFeedUrl: null
  blockedFeedUrl: null
  contextWindowSec: 900
  minConfidence: 0.4
  dailyLossCapPct: 0.1             # Baseline: revert to conservative 10% daily loss cap
  rewardSmoothing: 0.2

caching:
  dexscreenerPairsTtlSec: 10
  dexscreenerTrendingTtlSec: 60
  birdeyeMultiPriceTtlSec: 5
  birdeyeTrendingTtlSec: 60
  topicEmbeddingTtlSec: 600
social:
  neynar:
    enabled: true
    watchFids: []
    keywords: []
    pollIntervalSec: 15
  bluesky:
    enabled: true
    cursorPath: ./data/bluesky.cursor
    reconnectBackoffSec: 5
  reddit:
    enabled: true
    subreddits: [solana, solananft, memecoins, CryptoMoonShots, solanaMemeCoins, solanaMarkets, solanaCoin, solanaDeFi]
    pollIntervalSec: 45
    appType: installed
  telegram:
    enabled: true
    channels: []
    downloadDir: ./data/tdlib
    pollIntervalSec: 10
  gdelt:
    enabled: true
    pollIntervalSec: 900
alerts: {}
persistence:
  sqlitePath: ./data/trenches.db
  parquetDir: ./data/parquet
  parquetRollHours: 6
security:
  allowRemoteKillSwitch: false



positionManager:
  tipRangeLamports:
    min: 1500000
    max: 2500000
  autokill:
    flowRatioThreshold: 0.4          # Aggressive: More tolerance (was 0.6)
    uniquesDropThreshold: 3          # Aggressive: Less sensitive (was 1)
    safetyReasons:
      - missing_lp_mint
      - lp_supply_zero
      - lp_not_burned_or_locked
      - lp_locker_insufficient
      - lp_locker_lookup_failed
      - lp_insufficient
      - flow_ratio_low
      - uniques_low

providers:
  solanatracker:
    enabled: true
    baseUrl: https://api.solanatracker.io
    pollSec: 8
    ttlSec: 10
    endpoints:
      trending: true
      latest: true
      launchpads:
        pumpfun: true
        jupstudio: true


lunarcrush:
  enabled: true
  baseUrl: https://api.lunarcrush.com
  pollSec: 180
  mcpSseUrl: ''
  apiKey: ''
  endpoints:
    topics: /v2
    influencers: /v2
  sssBias:
    topicBoost: 0.03
    influencerBoost: 0.02
    maxBoost: 0.06


featuresJob:
  enabled: true
  intervalMs: 86400000
  embedder: bge-small-en
  lookbackHours: 24
  minPostsPerAuthor: 5

features:
  migrationWatcher: true
  rugGuard: true
  alphaRanker: true
  fillNet: true
  feeBandit: true
  constrainedSizing: true
  survivalStops: true
  offlinePolicyShadow: true
  jitoEnabled: false
  parquetExport: false
  flowCapRewrite: false
  constrainedRiskScaling: false
  orderIdRewardMatching: false
  
pyth:
  solUsdAccount: ''

priceUpdater:
  enabled: true
  intervalMs: 60000
  staleWarnSec: 300
  pythSolUsdPriceAccount: ""
