mode: SHADOW
logging:
  level: info
  json: true
services:
  agentCore:
    port: 4010
  executor:
    port: 4011
  uiGateway:
    port: 3000
  socialIngestor:
    port: 4012
  onchainDiscovery:
    port: 4013
  safetyEngine:
    port: 4014
  policyEngine:
    port: 4015
  positionManager:
    port: 4016
  narrativeMiner:
    port: 4017
  migrationWatcher:
    port: 4018
  leaderWallets:
    port: 4019
  featuresJob:
    port: 4020
  metrics:
    port: 8090
gating:
  sssMin: 0.6
  lpMinSol: 8                    # Aggressive: Lower liquidity for earlier entry (was 20)
  buysSellRatioMin: 1.5          # Aggressive: Allow more volatile tokens (was 2.2)
  uniquesMin: 6                  # Aggressive: Faster entry (was 12)
  minPoolAgeSec: 15              # Aggressive: Earlier entry (was 30)
  maxSpreadBps: 300              # Aggressive: Tolerate wider spreads (was 150)
watchWindows:
  durationSec: 1200
  refreshIntervalSec: 5
  decayHalfLifeSec: 120
topics:
  cluster:
    lshBands: 12
    lshRows: 6
    minCosine: 0.82
    mergeMinObservations: 3
  scoring:
    openThreshold: 0.6
    sustainThreshold: 0.45
    recencyHalfLifeSec: 120
    noveltyEpsilon: 0.000001
  phrase:
    minLength: 3
    maxLength: 48
    stopwords:
      - the
      - and
      - for
      - with
      - that
      - this
      - have
      - from
      - your
      - about
      - into
      - just
      - over
      - they
      - what
      - when
      - where
      - will
      - make
      - going
      - been
      - take
      - like
      - want
  matching:
    minTrieScore: 0.5
    minCosine: 0.75
    boostSymbolMatch: 0.15
    coolDownSec: 60
  baseline:
    halfLifeSec: 604800
    flushIntervalSec: 300
  test:
    enabled: false
ladders:
  takeProfits: [1.5, 2, 3, 5]
  multiplierPercents: [100, 300, 800, 2000]  # Aggressive: Let moonshots run (was [50, 100, 200, 400])
  trailActivatePct: 100                      # Aggressive: Let it run more (was 60)
  trailPct: 40                               # Aggressive: Wider trailing stops (was 28)
  hardStopLossPct: 35                        # Aggressive: Looser stop loss (was 22)
bandit:
  rewardHorizonMinutes: 30
  updateIntervalSec: 20
  epsilonFloor: 0.02
  bundles:
    - id: moonshot-hunter
      label: Moonshot Hunter
      gate: loose
      slippageBps: 500
      tipPercentile: p75
      sizeMultiplier: 1.5
    - id: vampire-attack
      label: Vampire Attack
      gate: loose
      slippageBps: 800
      tipPercentile: p90
      sizeMultiplier: 2.0
    - id: fast-entry
      label: Fast Entry
      gate: normal
      slippageBps: 300
      tipPercentile: p50
      sizeMultiplier: 1.0
    - id: alpha-chase
      label: Alpha Chase
      gate: loose
      slippageBps: 1000
      tipPercentile: p95
      sizeMultiplier: 1.2
wallet:
  reservesSol: 0.02
  dailySpendCapSol: 2.0              # Aggressive: 6x higher daily spending (was 0.30)
  autoSkimProfitSol: 0.5
  perNameCapFraction: 0.5            # Aggressive: 50% per token (was 0.3)
  perNameCapMaxSol: 15               # Aggressive: 3x higher max (was 5)
  lpImpactCapFraction: 0.03          # Aggressive: 2x LP impact (was 0.015)
  flowCapFraction: 0.6               # Aggressive: Higher flow capacity (was 0.4)
  equityTiers:
    - minEquity: 0
      maxEquity: 3
      riskFraction: 0.25             # Aggressive: 2x risk (was 0.12)
    - minEquity: 3
      maxEquity: 10
      riskFraction: 0.25             # Aggressive: 2x risk (was 0.12)
    - minEquity: 10
      maxEquity: 25
      riskFraction: 0.20             # Aggressive: 2.5x risk (was 0.08)
    - minEquity: 25
      maxEquity: 100
      riskFraction: 0.15             # Aggressive: 3x risk (was 0.05)
    - minEquity: 100
      maxEquity: null
      riskFraction: 0.10             # Aggressive: 3x risk (was 0.03)
  concurrencyCap: 8                  # Aggressive: More concurrent positions (was 3)
  concurrencyScaler:
    base: 1
    max: 1.4
    recoveryMinutes: 60
rpc:
  primaryUrl: http://127.0.0.1:8899
  secondaryUrl: ''
  wsUrl: ''
  jitoHttpUrl: ''
  jitoGrpcUrl: ''
  jupiterBaseUrl: https://quote-api.jup.ag/v6
  httpHeaders: {}
execution:
  tipStrategy: auto
  computeUnitPriceMode: auto_oracle
  migrationPreset:
    enabled: true
    durationMs: 60000
    cuPriceBump: 3000
    minSlippageBps: 100
    decayMs: 30000
  routeQuarantine:
    windowMinutes: 1440
    minAttempts: 8
    failRateThreshold: 0.25
    slipExcessWeight: 0.5
    failRateWeight: 100
dataProviders:
  neynarBaseUrl: https://api.neynar.com
  dexscreenerBaseUrl: https://api.dexscreener.com
  birdeyeBaseUrl: https://public-api.birdeye.so
  blueskyJetstreamUrl: wss://jetstream2.us-east.host.bsky.network
  gdeltPulseUrl: https://api.gdeltproject.org/api/v2/summary/summary
safety:
  lpBurnThreshold: 0.7             # Aggressive: Relaxed LP burn requirement (was 0.9)
  holderTopCap: 0.35               # Aggressive: Allow whale involvement (was 0.2)
  lockerPrograms:
    - 6z7H14RTa7tD1ynjUTduV1JN9WewtGku5Kz4DKftd84f
    - Lock111111111111111111111111111111111111111
    - 87AxbZcq7aj3HyCuXapnwXCfJLLq5yRvCNr4ieVsg7fR
  ignoreAccounts:
    - 1nc1nerator11111111111111111111111111111111
  candidateFeedUrl: null

policy:
  safeFeedUrl: null
  blockedFeedUrl: null
  contextWindowSec: 900
  minConfidence: 0.4
  dailyLossCapPct: 0.2             # Aggressive: Higher loss tolerance (was 0.1)
  rewardSmoothing: 0.2

caching:
  dexscreenerPairsTtlSec: 10
  dexscreenerTrendingTtlSec: 60
  birdeyeMultiPriceTtlSec: 5
  birdeyeTrendingTtlSec: 60
  topicEmbeddingTtlSec: 600
social:
  neynar:
    enabled: true
    watchFids: []
    keywords: []
    pollIntervalSec: 15
  bluesky:
    enabled: true
    cursorPath: ./data/bluesky.cursor
    reconnectBackoffSec: 5
  reddit:
    enabled: true
    subreddits: [solana, solananft, memecoins, CryptoMoonShots, solanaMemeCoins, solanaMarkets, solanaCoin, solanaDeFi]
    pollIntervalSec: 45
    appType: installed
  telegram:
    enabled: true
    channels: []
    downloadDir: ./data/tdlib
    pollIntervalSec: 10
  gdelt:
    enabled: true
    pollIntervalSec: 900
alerts: {}
persistence:
  sqlitePath: ./data/trenches.db
  parquetDir: ./data/parquet
  parquetRollHours: 6
security:
  allowRemoteKillSwitch: false



positionManager:
  tipRangeLamports:
    min: 1500000
    max: 2500000
  autokill:
    flowRatioThreshold: 0.4          # Aggressive: More tolerance (was 0.6)
    uniquesDropThreshold: 3          # Aggressive: Less sensitive (was 1)
    safetyReasons:
      - missing_lp_mint
      - lp_supply_zero
      - lp_not_burned_or_locked
      - lp_locker_insufficient
      - lp_locker_lookup_failed
      - lp_insufficient
      - flow_ratio_low
      - uniques_low

providers:
  solanatracker:
    enabled: true
    baseUrl: https://api.solanatracker.io
    pollSec: 8
    ttlSec: 10
    endpoints:
      trending: true
      latest: true
      launchpads:
        pumpfun: true
        jupstudio: true


lunarcrush:
  enabled: true
  baseUrl: https://api.lunarcrush.com
  pollSec: 180
  mcpSseUrl: ''
  apiKey: ''
  endpoints:
    topics: /v2
    influencers: /v2
  sssBias:
    topicBoost: 0.03
    influencerBoost: 0.02
    maxBoost: 0.06


featuresJob:
  enabled: true
  intervalMs: 86400000
  embedder: bge-small-en
  lookbackHours: 24
  minPostsPerAuthor: 5

features:
  migrationWatcher: true
  rugGuard: true
  alphaRanker: true
  fillNet: true
  feeBandit: true
  constrainedSizing: true
  survivalStops: true
  offlinePolicyShadow: true
  jitoEnabled: false
  parquetExport: false
  
pyth:
  solUsdAccount: ''

priceUpdater:
  enabled: true
  intervalMs: 60000
  staleWarnSec: 300
  pythSolUsdPriceAccount: ""

