# Q4 Memecoin Mania - Aggressive Trading Configuration
# Use with: NODE_ENV=q4-aggressive

# Fast execution with minimal delays
fastMode: true
quickEntry: true

# REDUCED SAFETY RESTRICTIONS FOR Q4 GAINS
safetyEngine:
  # Lower liquidity requirements for early entry
  gating:
    lpMinSol: 8                    # Was 20 SOL -> Now 8 SOL (400% more aggressive)
    buysSellRatioMin: 1.5          # Was 2.2 -> Now 1.5 (allow more volatile tokens)
    uniquesMin: 6                  # Was 12 -> Now 6 (faster entry)
    minPoolAgeSec: 15              # Was 30 -> Now 15 seconds (earlier entry)
    maxSpreadBps: 300              # Was 150 -> Now 300 (tolerate wider spreads)
  
  # Relaxed LP safety for memecoin season
  lpSafety:
    lpBurnThreshold: 0.7           # Was 0.9 -> Now 0.7 (70% burn requirement)
  
  # Relaxed holder concentration
  holderSafety:
    holderTopCap: 0.35             # Was 0.2 -> Now 0.35 (allow whale involvement)
  
  # More aggressive RugGuard tolerance
  rugguard:
    probabilityThreshold: 0.8      # Was 0.6 -> Now 0.8 (only block obvious rugs)
    skipAuthChecks: false          # Keep minimal authority checks

# AGGRESSIVE POSITION SIZING
policyEngine:
  # Increased daily limits for memecoin season
  wallet:
    dailySpendCapSol: 2.0          # Was 0.30 -> Now 2.0 SOL/day
    perNameCapFraction: 0.5        # Was 0.3 -> Now 0.5 (50% per token)
    perNameCapMaxSol: 15           # Was 5 -> Now 15 SOL per token
    lpImpactCapFraction: 0.03      # Was 0.015 -> Now 3% LP impact
    flowCapFraction: 0.6           # Was 0.4 -> Now 60% flow capacity
    concurrencyCap: 8              # Was 3 -> Now 8 concurrent positions
  
  # More aggressive alpha selection
  alphaRanking:
    alphaTopK: 25                  # Was 12 -> Now 25 (more opportunities)
    alphaMinScore: 0.4             # Was 0.52 -> Now 0.4 (lower bar)
  
  # Higher daily loss tolerance for higher gains
  risk:
    dailyLossCapPct: 0.2           # Was 0.1 -> Now 20% (double tolerance)
    dailyLossCapUsd: 1500          # Was 500 -> Now $1500
  
  # AGGRESSIVE RISK FRACTIONS (2x-3x increases)
  equityTiers:
    tier1: # 0-3 SOL
      riskFraction: 0.25           # Was 0.12 -> Now 25%
    tier2: # 3-10 SOL  
      riskFraction: 0.25           # Was 0.12 -> Now 25%
    tier3: # 10-25 SOL
      riskFraction: 0.20           # Was 0.08 -> Now 20%
    tier4: # 25-100 SOL
      riskFraction: 0.15           # Was 0.05 -> Now 15%
    tier5: # 100+ SOL
      riskFraction: 0.10           # Was 0.03 -> Now 10%

# RELAXED EXIT CONDITIONS FOR MOONSHOTS
positionManager:
  # Higher caps for memecoin season
  maxOpenPositions: 30             # Was 15 -> Now 30
  maxDailyNew: 200                 # Was 120 -> Now 200 new positions/day
  
  # Less restrictive exits (let winners run)
  ladderStops:
    trailActivatePct: 100          # Was 60% -> Now 100% (let it run more)
    trailPct: 40                   # Was 28% -> Now 40% (wider trailing stops)
    hardStopLossPct: 35            # Was 22% -> Now 35% (looser stop loss)
  
  # Modified ladder levels for moonshots
  ladderLevels:
    - profitPct: 100               # First exit at 100% (was 50%)
      exitPct: 15                  # Exit only 15% (was 25%)
    - profitPct: 300               # Second at 300% (was 200%)
      exitPct: 20                  # Exit 20%
    - profitPct: 800               # Third at 800% (was 400%)
      exitPct: 25                  # Exit 25%
    - profitPct: 2000              # Final at 2000% (moonshot territory)
      exitPct: 40                  # Keep 40% for ultimate moonshot
  
  # Relaxed autokill conditions
  autokill:
    flowRatioThreshold: 0.4        # Was 0.6 -> Now 0.4 (more tolerance)
    uniquesDropThreshold: 3        # Was 1 -> Now 3 (less sensitive)
  
  # Less aggressive survival stops
  survivalStops:
    hazardPanic: 0.95              # Was 0.85 -> Now 0.95 (higher panic threshold)
    hazardTighten: 0.8             # Was 0.65 -> Now 0.8 (less tightening)
    baseTrailBps: 200              # Was 120 -> Now 200 (2% base trail)
    minTrailBps: 100               # Was 60 -> Now 100 (1% min trail)
    maxTrailBps: 500               # Was 250 -> Now 500 (5% max trail)

# SPEED OPTIMIZATIONS
execution:
  # Faster confirmation requirements
  confirmationBlocks: 1            # Minimal confirmations
  slippageTolerance: 0.05          # 5% slippage tolerance
  priorityFee: "high"              # Always use high priority
  useJito: true                    # MEV protection for large orders
  
  # Aggressive bandit bundles
  bandits:
    moonshot:
      sizeMultiplier: 1.5          # 1.5x position sizes
      slippageBps: 500             # Accept 5% slippage
      priorityFee: "maximum"
    
    vampire:
      sizeMultiplier: 2.0          # 2x for clear alpha signals
      slippageBps: 800             # Accept 8% slippage
      priorityFee: "maximum"

# FASTER UPDATE INTERVALS
intervals:
  priceRefreshSec: 3               # Was 7 -> Now 3 seconds
  walletRefreshSec: 2              # Was 5 -> Now 2 seconds  
  congestionCheckSec: 1            # Was 3 -> Now 1 second
  policyEvalCacheSec: 10           # Was 30 -> Now 10 seconds

# SOCIAL SIGNAL AMPLIFICATION
socialIngestor:
  # More sensitive trend detection
  trendingThreshold: 0.3           # Lower threshold for trending
  velocityWeight: 2.0              # 2x weight on momentum
  noveltyBoost: 1.5                # 1.5x boost for new narratives

narrativeMiner:
  # Faster narrative detection
  minClusterSize: 3                # Smaller clusters = faster detection
  updateIntervalSec: 30            # More frequent updates
  trendBoostFactor: 2.0            # 2x boost for trending topics

# RATE LIMIT INCREASES
rateLimits:
  safetyEngine: 600                # Was 180 -> Now 600 req/min
  policyEngine: 720                # Was 240 -> Now 720 req/min
  positionManager: 600             # Was 180 -> Now 600 req/min

# Q4 MEMECOIN SEASON SPECIFIC
memeSeasonMode:
  enabled: true
  startDate: "2024-10-01"          # Q4 start
  endDate: "2024-12-31"            # Q4 end
  
  # Amplified signal weights during season
  socialSignalMultiplier: 1.5      # 1.5x social signals
  momentumBoost: 2.0               # 2x momentum weighting
  fomoPenalty: 0.5                 # Reduce FOMO penalties
  
  # Special memecoin detection
  memeKeywords:
    - "moon"
    - "pump" 
    - "mania"
    - "bull"
    - "rocket"
    - "gem"
    - "based"
    - "send"
    - "devs"
  
  # Narrative priority boosting
  hotNarratives:
    - "election"
    - "trump"
    - "musk"
    - "ai"
    - "crypto"
    - "solana"
    - "meta"