name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable corepack
        run: corepack enable
      - name: Install pnpm
        run: corepack prepare pnpm@9.12.3 --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Build services
        run: pnpm --filter "./services/*" run build
      - name: Build UI
        run: pnpm --filter "./apps/*" run build || true
      - name: Build tools
        run: pnpm --filter "./tools/*" run build || true
